image:
  file: .gitpod.Dockerfile

tasks:
  - name: Restore & Build
    init: |
      dotnet dev-certs https
      dotnet restore
      dotnet build
      echo 'TODO: build project'

vscode:
  extensions:
    - muhammad-sammy.csharp