image: 
  file: .gitpod.Dockerfile

tasks:
  - name: Restore & Build
    init: |
      cd ./ContosoCrafts
      dotnet restore
      dotnet build

  - name: Run
    env:
      ASPNETCORE_URLS: "http://+:5000"
      ASPNETCORE_HTTPS_URLS: "https://+:5001"
    command: |
      cd ./ContosoCrafts
      dotnet run

ports:
  - port: 5000
    onOpen: open-browser
  - port: 5001
    onOpen: open-browser

vscode:
  extensions:
    - muhammad-sammy.csharp