image: gitpod/workspace-dotnet:latest

tasks:
  - name: Setup
    before: |
      gp env ASPNETCORE_URLS=http://+:5000
      gp env ASPNETCORE_HTTPS_URLS=https://+:5001
    
  - name: Restore & Build
    init: |
      cd ./ContosoCrafts
      dotnet dev-certs https
      dotnet restore
      dotnet build
      echo 'TODO: build project'

  - name: Run
    command: |
      cd ./ContosoCrafts
      dotnet run

ports:
- port: 5000
- port: 5001

vscode:
  extensions:
    - muhammad-sammy.csharp