image: 
  file: .gitpod.Dockerfile

tasks:
  - name: Restore & Build
    init: |
      cd ./ContosoCrafts
      dotnet restore
      dotnet build

  - name: Run
    command: |
      cd ./ContosoCrafts
      dotnet run

ports:
  - port: 5000
    onOpen: open-browser

vscode:
  extensions:
    - muhammad-sammy.csharp
