image: 
  file: .gitpod.Dockerfile

tasks:
  - name: Restore & Build
    init: |
      cd ./ContosoCrafts
      dotnet dev-certs https
      dotnet restore
      dotnet build
      echo 'TODO: build project'

  - name: Run
    command: |
      cd ./ContosoCrafts
      dotnet run

ports:
  - port: 5000
    onOpen: open-browser
  - port: 5001
    onOpen: open-browser

vscode:
  extensions:
    - muhammad-sammy.csharp